### ISSUE TITLE
Detect User stopped drawing

### ISSUE THREAD

**Issue by jaytj95** [RiccardoMoro/FreeDrawView#2]
How can we detect if the user has stopped drawing?

**Comment by RiccardoMoro** [comment]
You can set a PathDrawnListener that will be notified every time the user finishes to draw a line (releasing it's finger)

**Comment by jaytj95** [comment]
Is there a way to check if the user is currently drawing (having their finger down)?

**Comment by RiccardoMoro** [comment]
Nope, but that's a nice enchantment
I will do it as soon as I can, in the path drawn listener I'm gonna add an onPathDrawStart or something like that, is this what you mean?
Next week

**Comment by jaytj95** [comment]
Check PR #3. I did this for you :)

**Comment by RiccardoMoro** [comment]
Wow thanks!
May I ask why you downgraded the sdk version from 25 to 23?

**Comment by jaytj95** [comment]
Sorry. I did this because of some incompatibility with a project I was
working on! I didn't realize my change propagated up to the forked repo I
made.

**Comment by RiccardoMoro** [comment]
Ok, no problem. When I'll be back from work I'm gonna restore the sdk version and merge your pull request
Thanks again!

**Comment by RiccardoMoro** [comment]
Merged!
