### ISSUE TITLE
Possible enchancement

### ISSUE THREAD

**Issue by kal27** [RiccardoMoro/FreeDrawView#4]
Could we perhaps make FreeDrawView an ImageView?
This could be useful when drawing on pictures.
I have tried making FreeDrawView extend ImageView rather than simple view but then setImageBitmap method of ImageView did not work - the background would not change.

**Comment by RiccardoMoro** [comment]
closing this issue, you can keep track of the progress here https://github.com/RiccardoMoro/FreeDrawView/issues/8
