### ISSUE TITLE
Error if setOnPathDrawnListener() is not called

### ISSUE THREAD

**Issue by csbenz** [RiccardoMoro/FreeDrawView#6]
Without calling `setOnPathDrawnListener()` on the `FreeDrawView`, I get an error:

> java.lang.NullPointerException: Attempt to invoke interface method 'void com.rm.freedrawview.PathDrawnListener.onPathStart()' on a null object reference

Once I call the method, even while leaving the callbacks empty, everything is fine.

**Comment by RiccardoMoro** [comment]
Damn, it's an error in the pull request I accepted few days ago.
I'm fixing it right now, thanks for the feedback

**Comment by RiccardoMoro** [comment]
Fixed!
v1.0.2
Thanks again, closing

**Comment by csbenz** [comment]
Great work, thanks!
