### ISSUE TITLE
Make possible to add a Bitmap to FreeDrawView

### ISSUE THREAD

**Issue by csbenz** [RiccardoMoro/FreeDrawView#8]
To be able to edit an old drawing.

**Comment by RiccardoMoro** [comment]
You mean restore a previous state from a FreeDrawView?

**Comment by csbenz** [comment]
I'm saving the drawings as Bitmaps in memory. When the user wants to edit a
drawing, the library gives no option to start from the said Bitmap to be
able to edit it.

**Comment by RiccardoMoro** [comment]
Mmm I was thinking, it would be easier if I just give you a method `public Parcelable getViewState()` which gives a Parcelable containing the FreeDrawView state and a `public void restoreStateFromParcelable(Parcelable parcelable)` which given the Parcelable restores the View state, would that be good for you? (for now, I'll be working on the bitmap thing with the [https://github.com/RiccardoMoro/FreeDrawView/issues/5](eraser) issue)

**Comment by csbenz** [comment]
That would be helpful, except for multi-platform apps. I'm saving the drawing in a cloud database and have to be able to recuperate it anywhere (eg PC). Still, I could store both the bitmap and the Parcelable State.

**Comment by RiccardoMoro** [comment]
Yes, you're right, I didn't think of multi-platform apps, my bad..
As a fast solution I can add the Parcelable save-restore today, and with time I'll add the option to restore from a Bitmap, would that be ok?

**Comment by csbenz** [comment]
Yes, fine! :) thanks for your work

**Comment by RiccardoMoro** [comment]
Slowly working on this... I'm very busy working lately sorry
I've made the method to get a Parcelable of the saved state, but than when I tried to write it inside a File I had an error doing myParcelable.marshall() because of the size of the Parcelable itself..
I'm trying something else in the next few days

**Comment by csbenz** [comment]
Thanks for the update and for working on this issue.

**Comment by RiccardoMoro** [comment]
@csbenz (Finally) I'm about to release the save-restore functionality. (in v1.1.0, I'll push it on bintray in about an hour)
With the getCurrentViewStateAsSerializable() you can get the draw state as a Serializable 
And with restoreStateFromSerializable(FreeDrawSerializableState state) you can restore it. 

Let me know if you find any problem with this new functionality 
Check out the new readme just above the View attributes section to see more 

Thank you for the patience, Riccardo

**Comment by RiccardoMoro** [comment]
Closing this issue, let me know id you are having problems
