### ISSUE TITLE
Listeners Not Working !

### ISSUE THREAD

**Issue by hardz** [RiccardoMoro/FreeDrawView#9]
Thanks for this Awesome Work !
I found this two Listeners not working as it has to be !
removePathDrawnListener and setPathRedoUndoCountChangeListener either setting it null manually not making any change.

mFreeDrawView.setOnPathDrawnListener(null);
mFreeDrawView.setPathRedoUndoCountChangeListener(null);

i want to stop drawing when user done with it on button click event.
any ways to do it ?

**Comment by RiccardoMoro** [comment]
You want to make impossible for the user to draw on the FreeDrawView right?
@hardz

**Comment by hardz** [comment]
Yes ! I achieved it by simple trick mFreeDrawView.setEnabled(true); for allowing to draw and mFreeDrawView.setEnabled(false); for stop drawing(impossible for user to draw) .

**Comment by RiccardoMoro** [comment]
That's the right way to do it, not a trick :)
Those listener are meant to notify you about changes, not disable the View
Thanks, closing!
